os:
  - linux
  - osx

dist: xenial

language: c++

addons:
  apt:
    packages:
      - bison
      - flex
      - curl
      - make
      - texinfo
      - zlib1g-dev
      - tar
      - bzip2
      - gzip
      - xz-utils
      - unzip
      - dos2unix
      - libtool-bin
  homebrew:
    update: true
    packages:
      - bison
      - flex
      - curl
      - make
      - texinfo
      - zlib
      - bzip2
      - gzip
      - xz
      - unzip
      - dos2unix
      - libtool

compiler:
  - gcc
  - clang

env:
  - TARGET=i586-pc-msdosdjgpp PACKAGES="binutils gcc djgpp-2.05"
  - TARGET=i586-pc-msdosdjgpp PACKAGES="binutils gcc djgpp-cvs"
  - TARGET=i586-pc-msdosdjgpp PACKAGES="gdb"
  - TARGET=arm-eabi           PACKAGES="binutils gcc newlib"
  - TARGET=arm-eabi           PACKAGES="gdb"
  - TARGET=avr                PACKAGES="binutils gcc avr-libc"
  - TARGET=avr                PACKAGES="gdb avarice simulavr avrdude"
  - TARGET=ia16               PACKAGES="binutils gcc newlib"

before_install:
#  - if [ $TRAVIS_OS_NAME = 'linux' ] && [ $CC = 'clang' ] ; then sudo apt-get -y install ; fi
#  - if [ $TRAVIS_OS_NAME = 'osx' ] && [ $CC = 'clang' ]; then brew install ; fi

script:
  - ./script/test.sh
